import React from 'react';
import { SnakeGame } from './components/SnakeGame';
import { Github } from 'lucide-react';

const App: React.FC = () => {
  return (
    <div className="min-h-screen bg-gray-900 text-white font-sans selection:bg-cyan-500 selection:text-black">
      {/* Header */}
      <header className="py-6 border-b border-gray-800 bg-gray-900/50 backdrop-blur-md sticky top-0 z-10">
        <div className="container mx-auto px-4 flex items-center justify-between">
            <div className="flex items-center gap-2">
                <div className="w-8 h-8 bg-gradient-to-br from-cyan-400 to-purple-600 rounded-lg shadow-lg flex items-center justify-center">
                    <span className="font-bold text-white text-lg">S</span>
                </div>
                <h1 className="text-xl font-bold tracking-tight bg-clip-text text-transparent bg-gradient-to-r from-gray-100 to-gray-400">
                    Snake <span className="text-cyan-400">AI</span>
                </h1>
            </div>
            <div className="text-xs text-gray-500 border border-gray-800 px-3 py-1 rounded-full bg-gray-900">
               Powered by Gemini 2.5
            </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="container mx-auto px-4 py-8 flex flex-col items-center justify-center min-h-[calc(100vh-160px)]">
        <SnakeGame />
      </main>

      {/* Footer */}
      <footer className="py-6 border-t border-gray-800 text-center text-gray-500 text-sm">
        <p className="flex items-center justify-center gap-2">
            Retro arcade vibes generated by React & Tailwind
        </p>
      </footer>
    </div>
  );
};

export default App;